name: Chromatic
on: push
    
jobs:

  chromatic-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn --frozen-lockfile
      - run: yarn run chromatic --only-changed
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
